const express = require("express");
const router = express.Router();
const al = require("./representatives/al");
const ak = require("./representatives/ak");
const az = require("./representatives/az");
const ar = require("./representatives/ar");
const ca = require("./representatives/ca");
const co = require("./representatives/co");
const ct = require("./representatives/ct");
const de = require("./representatives/de");
const fl = require("./representatives/fl");
const ga = require("./representatives/ga");
const hi = require("./representatives/hi");
const id = require("./representatives/id");
const il = require("./representatives/il");
const ind = require("./representatives/in");
const ia = require("./representatives/ia");
const ks = require("./representatives/ks");
const ky = require("./representatives/ky");
const la = require("./representatives/la");
const me = require("./representatives/me");
const md = require("./representatives/md");
const ma = require("./representatives/ma");
const mi = require("./representatives/mi");
const mn = require("./representatives/mn");
const ms = require("./representatives/ms");
const mo = require("./representatives/mo");
const mt = require("./representatives/mt");
const ne = require("./representatives/ne");
const nv = require("./representatives/nv");
const nh = require("./representatives/nh");
const nj = require("./representatives/nj");
const nm = require("./representatives/nm");
const ny = require("./representatives/ny");
const nc = require("./representatives/nc");
const nd = require("./representatives/nd");
const oh = require("./representatives/oh");
const ok = require("./representatives/ok");
const or = require("./representatives/or");
const pa = require("./representatives/pa");
const ri = require("./representatives/ri");
const sc = require("./representatives/sc");
const sd = require("./representatives/sd");
const tn = require("./representatives/tn");
const tx = require("./representatives/tx");
const ut = require("./representatives/ut");
const vt = require("./representatives/vt");
const va = require("./representatives/va");
const vi = require("./representatives/vi");
const wa = require("./representatives/wa");
const wv = require("./representatives/wv");
const wi = require("./representatives/wi");
const wy = require("./representatives/wy");
const als = require("./senators/al");
const aks = require("./senators/ak");
const azs = require("./senators/az");
const ars = require("./senators/ar");
const cas = require("./senators/ca");
const cos = require("./senators/co");
const cts = require("./senators/ct");
const des = require("./senators/de");
const fls = require("./senators/fl");
const gas = require("./senators/ga");
const his = require("./senators/hi");
const ids = require("./senators/id");
const ils = require("./senators/il");
const inds = require("./senators/in");
const ias = require("./senators/ia");
const kss = require("./senators/ks");
const kys = require("./senators/ky");
const las = require("./senators/la");
const mes = require("./senators/me");
const mds = require("./senators/md");
const mas = require("./senators/ma");
const mis = require("./senators/mi");
const mns = require("./senators/mn");
const mss = require("./senators/ms");
const mos = require("./senators/mo");
const mts = require("./senators/mt");
const nes = require("./senators/ne");
const nvs = require("./senators/nv");
const nhs = require("./senators/nh");
const njs = require("./senators/nj");
const nms = require("./senators/nm");
const nys = require("./senators/ny");
const ncs = require("./senators/nc");
const nds = require("./senators/nd");
const ohs = require("./senators/oh");
const oks = require("./senators/ok");
const ors = require("./senators/or");
const pas = require("./senators/pa");
const ris = require("./senators/ri");
const scs = require("./senators/sc");
const sds = require("./senators/sd");
const tns = require("./senators/tn");
const txs = require("./senators/tx");
const uts = require("./senators/ut");
const vts = require("./senators/vt");
const vas = require("./senators/va");
const vis = require("./senators/vi");
const was = require("./senators/wa");
const wvs = require("./senators/wv");
const wis = require("./senators/wi");
const wys = require("./senators/wy");
router.get("/al", al);
router.get("/ak", ak);
router.get("/az", az);
router.get("/ar", ar);
router.get("/ca", ca);
router.get("/co", co);
router.get("/ct", ct);
router.get("/de", de);
router.get("/fl", fl);
router.get("/ga", ga);
router.get("/hi", hi);
router.get("/id", id);
router.get("/il", il);
router.get("/in", ind);
router.get("/ia", ia);
router.get("/ks", ks);
router.get("/ky", ky);
router.get("/la", la);
router.get("/me", me);
router.get("/md", md);
router.get("/ma", ma);
router.get("/mi", mi);
router.get("/mn", mn);
router.get("/ms", ms);
router.get("/mo", mo);
router.get("/mt", mt);
router.get("/ne", ne);
router.get("/nv", nv);
router.get("/nh", nh);
router.get("/nj", nj);
router.get("/nm", nm);
router.get("/ny", ny);
router.get("/nc", nc);
router.get("/nd", nd);
router.get("/oh", oh);
router.get("/ok", ok);
router.get("/or", or);
router.get("/pa", pa);
router.get("/ri", ri);
router.get("/sc", sc);
router.get("/sd", sd);
router.get("/tn", tn);
router.get("/tx", tx);
router.get("/ut", ut);
router.get("/va", va);
router.get("/vi", vi);
router.get("/vt", vt);
router.get("/wa", wa);
router.get("/wv", wv);
router.get("/wi", wi);
router.get("/wy", wy);
router.get("/als", als);
router.get("/aks", aks);
router.get("/azs", azs);
router.get("/ars", ars);
router.get("/cas", cas);
router.get("/cos", cos);
router.get("/cts", cts);
router.get("/des", des);
router.get("/fls", fls);
router.get("/gas", gas);
router.get("/his", his);
router.get("/ids", ids);
router.get("/ils", ils);
router.get("/ins", inds);
router.get("/ias", ias);
router.get("/kss", kss);
router.get("/kys", kys);
router.get("/las", las);
router.get("/mes", mes);
router.get("/mds", mds);
router.get("/mas", mas);
router.get("/mis", mis);
router.get("/mns", mns);
router.get("/mss", mss);
router.get("/mos", mos);
router.get("/mts", mts);
router.get("/nes", nes);
router.get("/nvs", nvs);
router.get("/nhs", nhs);
router.get("/njs", njs);
router.get("/nms", nms);
router.get("/nys", nys);
router.get("/ncs", ncs);
router.get("/nds", nds);
router.get("/ohs", ohs);
router.get("/oks", oks);
router.get("/ors", ors);
router.get("/pas", pas);
router.get("/ris", ris);
router.get("/scs", scs);
router.get("/sds", sds);
router.get("/tns", tns);
router.get("/txs", txs);
router.get("/uts", uts);
router.get("/vas", vas);
router.get("/vis", vis);
router.get("/vts", vts);
router.get("/was", was);
router.get("/wvs", wvs);
router.get("/wis", wis);
router.get("/wys", wys);

module.exports = router;